import telebot
import schedule
import time
import threading
import requests
import random
import os
from datetime import datetime, timedelta
from keep_alive import keep_alive
from deep_translator import GoogleTranslator

# --- 設定區 ---
TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN')
TARGET_CHAT_ID = os.environ.get('TARGET_CHAT_ID')

bot = telebot.TeleBot(TOKEN)

# --- 功能區 ---
def get_weekly_trending(count=6):
    last_week = (datetime.now() - timedelta(days=7)).strftime('%Y-%m-%d')
    url = f"https://api.github.com/search/repositories?q=created:>{last_week}&sort=stars&order=desc"
    
    try:
        headers = {'User-Agent': 'Python Bot'}
        response = requests.get(url, headers=headers)
        data = response.json()
        
        results = []
        
        if 'items' in data and len(data['items']) > 0:
            pool_size = min(len(data['items']), 50)
            sample_size = min(pool_size, count)
            selected_repos = random.sample(data['items'][:pool_size], sample_size)
            
            for repo in selected_repos:
                original_desc = repo['description'] if repo['description'] else "無簡介"
                
                try:
                    translated_desc = GoogleTranslator(source='auto', target='zh-TW').translate(original_desc)
                except Exception:
                    translated_desc = original_desc
                
                if len(translated_desc) > 100:
                    translated_desc = translated_desc[:97] + "..."

                # --- 這裡修改了邏輯：抓取 Topics (標籤) ---
                topics = repo.get('topics', [])
                if topics:
                    # 如果有標籤，只取前 3 個 (太長會很醜)，並用逗號連接
                    # 例如: "react, dashboard, admin"
                    tags_display = ", ".join(topics[:3])
                else:
                    # 如果開發者懶惰沒寫標籤，我們才退而求其次顯示語言
                    tags_display = repo['language'] if repo['language'] else "通用工具"

                results.append({
                    "name": repo['name'],
                    "full_name": repo['full_name'],
                    "desc": translated_desc,
                    "tags": tags_display, # 把原本的 language 改成 tags
                    "stars": f"{repo['stargazers_count']:,}",
                    "link": repo['html_url']
                })
                
            return results
        return []
    except Exception as e:
        print(f"GitHub API Error: {e}")
        return []

def send_weekly_report():
    if not TARGET_CHAT_ID:
        print("尚未設定 Chat ID")
        return

    print("正在準備週報...")
    repos = get_weekly_trending(count=6)
    
    if repos:
        title_date = datetime.now().strftime('%Y/%m/%d')
        msg = f"🗞 **GitHub 開源週報** | {title_date}\n"
        msg += "━━━━━━━━━━━━━━━━━━\n\n"
        
        for i, repo in enumerate(repos, 1):
            msg += (
                f"**{i}. {repo['name']}**\n"
                # 這裡改成了顯示 tags，並換了圖示
                f"`⭐️ {repo['stars']} `  f" `🏷️ {repo['tags']}`\n" 
                f"> 💡 {repo['desc']}\n"
                f"🔗 [點此查看專案內容]({repo['link']})\n\n"
            )
            
        msg += "━━━━━━━━━━━━━━━━━━\n"
        msg += "🤖 _Generated by Auto-Bot_ | #GitHub #OpenSource"

        try:
            bot.send_message(TARGET_CHAT_ID, msg, parse_mode='Markdown', disable_web_page_preview=True)
            print("週報已發送")
        except Exception as e:
            print(f"發送失敗: {e}")
    else:
        print("抓取資料失敗")

# --- 指令區 ---
@bot.message_handler(commands=['start'])
def handle_start(message):
    bot.reply_to(message, f"Chat ID: `{message.chat.id}`", parse_mode='Markdown')

@bot.message_handler(commands=['test'])
def handle_test(message):
    bot.reply_to(message, "🎨 正在搜尋並抓取標籤資料，請稍等...")
    global TARGET_CHAT_ID
    temp_old_id = TARGET_CHAT_ID
    TARGET_CHAT_ID = message.chat.id
    send_weekly_report()
    TARGET_CHAT_ID = temp_old_id

# --- 排程區 ---
schedule.every().monday.at("01:00").do(send_weekly_report)

def schedule_checker():
    while True:
        schedule.run_pending()
        time.sleep(1)

if __name__ == "__main__":
    keep_alive() 
    threading.Thread(target=schedule_checker).start() 
    bot.infinity_polling()
